name: Build Windows EXE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.2'

      - name: Build exe
        run: go build -ldflags="-s -w" -o idbtool.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: idbtool-windows
          path: idbtool.exe
